### ISSUE TITLE
event todos

### ISSUE THREAD

**Issue by filtercake** [filtercake/orga#64]
nice list :)

#### TODOs
- [ ] :calendar: Agree on a date 
- [ ] :memo: Create ti.to page
- [ ] :school: :bear: Post event on nodeschool.io  
- [ ] :octocat: Inform on GiHub 
- [ ] :monkey_face: :envelope: Inform about event through mail chimp
- [ ] :bird: Tweet about the event
- [ ] :house: Update homepage 
- [ ] :alarm_clock: Send reminder to participants at the day of event 

/v nodeschool/ berlin/ issues/ 27

**Comment by filtercake** [comment]
vertsion:

#### TODOs
- [ ] :octocat: open issue
- [ ] :calendar: Agree on a date => doodle
- [ ] :memo: registration => ti.to
- [ ] :school: :bear: Post event on calender(s)
- [ ] :monkey_face: :envelope: Send newsletter => Mailchimp
- [ ] :bird: Tweet about the event
- [ ] :house: Update homepage 
- [ ] :alarm_clock: Send reminder to participants at the day before event
